// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhF81Wmr1UzXTu-QccmVv27nFThS9NYU',
    appId: '1:1034012150961:web:d3364968dde318f4cde690',
    messagingSenderId: '1034012150961',
    projectId: 'fir-test-project-a19ff',
    authDomain: 'fir-test-project-a19ff.firebaseapp.com',
    storageBucket: 'fir-test-project-a19ff.appspot.com',
    measurementId: 'G-GGFVEGYFK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeV9d-z30dXOY0rqqYA-v8AayLDxVPCQ',
    appId: '1:1034012150961:android:04104930cd1d2a26cde690',
    messagingSenderId: '1034012150961',
    projectId: 'fir-test-project-a19ff',
    storageBucket: 'fir-test-project-a19ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YSAhAd0T6rfL__zEOAIab-hpzSUds4o',
    appId: '1:1034012150961:ios:0993269605abb099cde690',
    messagingSenderId: '1034012150961',
    projectId: 'fir-test-project-a19ff',
    storageBucket: 'fir-test-project-a19ff.appspot.com',
    iosClientId: '1034012150961-998qab1cf4ltnij759a0jnbhgci4iiqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetestproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YSAhAd0T6rfL__zEOAIab-hpzSUds4o',
    appId: '1:1034012150961:ios:0993269605abb099cde690',
    messagingSenderId: '1034012150961',
    projectId: 'fir-test-project-a19ff',
    storageBucket: 'fir-test-project-a19ff.appspot.com',
    iosClientId: '1034012150961-998qab1cf4ltnij759a0jnbhgci4iiqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetestproject',
  );
}
